package com.ase.gymjudge.controller;
//import org.springframework.http.ResponseEntity;
import com.ase.gymjudge.entities.Admin;
import com.ase.gymjudge.entities.Competition;
import com.ase.gymjudge.repositories.AdminRepository;
import com.ase.gymjudge.repositories.CompetitionRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;

@Controller
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AdminRepository adminRepository;
    @Autowired
    private CompetitionRepository compRepository;


    @RequestMapping(value = { "/", "/register" }, method = RequestMethod.GET)
    public String showSignUpForm(Model model) {
        Admin newAdmin = new Admin();
        model.addAttribute("newAdmin", newAdmin);
        return "addAdmin";
    }
    @PostMapping("/addadmin")
    public String addUser(@Valid Admin newAdmin, BindingResult result, Model model) {
        if (result.hasErrors()) {
            return "addAdmin";
        }
        adminRepository.save(newAdmin);
        return "showCompetitions";
    }
    @RequestMapping(value = { "/addcompetition" }, method = RequestMethod.GET)
    public String createNewCompetition(Model model) {
        Competition competition = new Competition();
        model.addAttribute("competition", competition);
        return "addCompetition";
    }
    @PostMapping("/addcompetition")
    public String addCompetition(@Valid Competition competition, BindingResult result, Model model) {
        if (result.hasErrors()) {
            return "addCompetition";
        }
        compRepository.save(competition);
        model.addAttribute("competitions", compRepository.findAll());
        return "showCompetitions";
    }
    @GetMapping("/competitions")
    public String showCompetitions(Competition competition, Model model) {
        model.addAttribute("competitions", compRepository.findAll());
        return "showCompetitions";
    }


}
